import type { WorkoutType } from '../domain/workoutTypes';

// Centralized static UI copy. Dynamic recommendation/schedule text generated by
// src/domain/schedule.ts and src/data/julyPlan.ts is NOT duplicated here — those
// modules own their own wording and are already covered by their own tests.

export const SAFETY_NOTICE_FULL =
  '痛み、めまい、吐き気、胸痛、強い違和感がある場合は、すぐに運動を中止してください。このアプリは医療アドバイスではありません。';

export const SAFETY_NOTICE_COMPACT =
  '痛み、めまい、吐き気、胸痛、強い違和感がある場合は、すぐに運動を中止してください。';

export const ONBOARDING_INTRO =
  '7月は助走で十分です。試験勉強を壊さず、8月に向けて身体を起こしましょう。';

export function getCompletionMessage(workoutType: WorkoutType): string {
  if (workoutType === 'rest') {
    return '休息も計画の一部です。明日戻れば大丈夫です。';
  }
  if (workoutType === 'short') {
    return '10分版でつなげました。試験月ではこれも完全に成功です。';
  }
  return '今日はこれで十分です。試験月の目的は、途切れさせないことです。';
}

export const WORKOUT_NEXT_STEP_HINT = '次回はA/Bを交互に、無理のない範囲で続けましょう。';

export function getMonthlyAchievementLine(monthlyCount: number): string {
  if (monthlyCount <= 1) {
    return '7月最初の一歩です。ここからで十分です。';
  }
  return `今月${monthlyCount}回目の実施です。着実に積み上がっています。`;
}

export const EXAM_MODE_HELPER_TEXT = 'ONの間は、10分版や休息を積極的に提案します。';

export const AUGUST_PREVIEW_TITLE = '8月以降について';
export const AUGUST_PREVIEW_BODY =
  '7月の助走が十分にできると、8月から本格強化モードを解放できます。今は途切れさせないことを優先しましょう。';

export const RESET_CONFIRM_TEXT = '本当にすべての記録を削除しますか？この操作は元に戻せません。';

export const NUTRITION_EXPLAINER_TITLE = '体重別の目標について';
export const NUTRITION_EXPLAINER_BODY =
  '7月の目安は体重×1.4〜1.6gです。一般的な運動者の参考範囲は体重×1.4〜2.0g/日とされています。プロテインは食事の代替ではなく、不足分を埋める道具として使いましょう。';

export const REMINDER_BANNER_TITLE = '今日はまだ記録がありません';
export const REMINDER_BANNER_BODY = '今日は10分だけで十分です。勉強の合間に軽く動きましょう。';

export const CALENDAR_LEGEND_HINT = '色とアイコンの両方で状態を表しています。';
