import type { WorkoutType, PerceivedEffort } from '../domain/workoutTypes';
import type { ConfidenceLevel, ExamFormat, FiveLevelScale, MaterialStatus } from '../domain/study/studyTypes';

// Centralized static UI copy. Dynamic recommendation/schedule text generated by
// src/domain/schedule.ts and src/data/julyPlan.ts is NOT duplicated here — those
// modules own their own wording and are already covered by their own tests.

export const SAFETY_NOTICE_FULL =
  '痛み、めまい、吐き気、胸痛、強い違和感がある場合は、すぐに運動を中止してください。このアプリは医療アドバイスではありません。';

export const SAFETY_NOTICE_COMPACT =
  '痛み、めまい、吐き気、胸痛、強い違和感がある場合は、すぐに運動を中止してください。';

export const ONBOARDING_INTRO =
  '7月は助走で十分です。試験勉強を壊さず、8月に向けて身体を起こしましょう。';

export function getCompletionMessage(workoutType: WorkoutType): string {
  if (workoutType === 'rest') {
    return '休息も計画の一部です。明日戻れば大丈夫です。';
  }
  if (workoutType === 'short') {
    return '10分版でつなげました。試験月ではこれも完全に成功です。';
  }
  return '今日はこれで十分です。試験月の目的は、途切れさせないことです。';
}

export const WORKOUT_NEXT_STEP_HINT = '次回はA/Bを交互に、無理のない範囲で続けましょう。';

export function getMonthlyAchievementLine(monthlyCount: number): string {
  if (monthlyCount <= 1) {
    return '7月最初の一歩です。ここからで十分です。';
  }
  return `今月${monthlyCount}回目の実施です。着実に積み上がっています。`;
}

export const EXAM_MODE_HELPER_TEXT = 'ONの間は、10分版や休息を積極的に提案します。';

export const AUGUST_PREVIEW_TITLE = '8月以降について';
export const AUGUST_PREVIEW_BODY =
  '7月の助走が十分にできると、8月から本格強化モードを解放できます。今は途切れさせないことを優先しましょう。';

export const RESET_CONFIRM_TEXT = '本当にすべての記録を削除しますか？この操作は元に戻せません。';

export const NUTRITION_EXPLAINER_TITLE = '体重別の目標について';
export const NUTRITION_EXPLAINER_BODY =
  '7月の目安は体重×1.4〜1.6gです。一般的な運動者の参考範囲は体重×1.4〜2.0g/日とされています。プロテインは食事の代替ではなく、不足分を埋める道具として使いましょう。';

export const REMINDER_BANNER_TITLE = '今日はまだ記録がありません';
export const REMINDER_BANNER_BODY = '今日は10分だけで十分です。勉強の合間に軽く動きましょう。';

export const CALENDAR_LEGEND_HINT = '色とアイコンの両方で状態を表しています。';

export const EFFORT_LABEL: Record<PerceivedEffort, string> = {
  easy: '軽い',
  good: 'ちょうどよい',
  hard: 'きつい',
  too_hard: 'きつすぎた',
};

export const NO_RECORD_FOR_DAY_TEXT = 'この日はまだ記録がありません。';

export const IMPORT_EXPORT_FIRST_HINT =
  '読み込むと、現在の記録は選択したファイルの内容で上書きされます。念のため、先に「データを書き出す」で現在の記録をバックアップしておくことをおすすめします。';

export const IMPORT_OVERWRITE_CONFIRM_TEXT =
  '現在のデータを、選択したファイルの内容で上書きします。よろしいですか？';

export const IMPORT_INVALID_FILE_TEXT = 'JSONファイルを読み込めませんでした。ファイルの形式を確認してください。';

export const BODY_HUB_WORKOUT_TITLE = 'トレーニング';
export const BODY_HUB_WORKOUT_SUBTITLE = '今日のメニューを実行する';
export const BODY_HUB_NUTRITION_TITLE = '栄養・プロテイン';
export const BODY_HUB_NUTRITION_SUBTITLE = 'タンパク質の記録と目標を確認する';

export const STUDY_OVERVIEW_INTRO =
  '試験日・範囲・資料が分からないままでも大丈夫です。まずは何が分かっていないかを整理するところから始めます。';

export const STUDY_COURSES_TITLE = '科目';
export const STUDY_COURSES_SUBTITLE = '科目を登録する';
export const STUDY_EXAMS_TITLE = '試験情報';
export const STUDY_EXAMS_SUBTITLE = '試験日・範囲の確信度を整理する';
export const STUDY_MATERIALS_TITLE = '教材';
export const STUDY_MATERIALS_SUBTITLE = '資料の有無を確認する';
export const STUDY_DISCOVERY_TITLE = 'Discovery Tasks';
export const STUDY_DISCOVERY_SUBTITLE = '準備中(Phase 4-Bで実装予定)';
export const STUDY_AVAILABILITY_TITLE = '固定予定';
export const STUDY_AVAILABILITY_SUBTITLE = '準備中(Phase 4-Cで実装予定)';

export const STUDY_NO_COURSES_TEXT = 'まだ科目が登録されていません。先に科目を登録してください。';
export const STUDY_GO_TO_COURSES_BUTTON = '科目を登録する';

export const CONFIDENCE_LEVEL_OPTIONS: { value: ConfidenceLevel; label: string }[] = [
  { value: 'unknown', label: '不明' },
  { value: 'low', label: '低い' },
  { value: 'medium', label: '中程度' },
  { value: 'confirmed', label: '確定' },
];

export const EXAM_FORMAT_OPTIONS: { value: ExamFormat; label: string }[] = [
  { value: 'written', label: '筆記' },
  { value: 'oral', label: '口頭' },
  { value: 'report', label: 'レポート' },
  { value: 'unknown', label: '不明' },
];

export const FIVE_LEVEL_OPTIONS: { value: FiveLevelScale; label: string }[] = [
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
];

export const MATERIAL_STATUS_OPTIONS: { value: MaterialStatus; label: string }[] = [
  { value: 'missing', label: '未確認' },
  { value: 'partial', label: '一部確認' },
  { value: 'complete', label: '確認済み' },
  { value: 'not_applicable', label: '対象外(存在しない)' },
];

export const MATERIAL_NOT_APPLICABLE_HELPER_TEXT =
  'この科目には存在しない、または不要と確認済みとして扱います。';

export const COURSE_DELETE_WARNING_TEXT =
  'この科目に関連する試験情報・教材情報・Discovery Taskも削除されます。';

export const EXAM_INFO_CLEAR_CONFIRM_TEXT = '試験情報をクリアします。よろしいですか？';
